---
title: "Práctica 2: Limpieza y validación de los datos"
author: ' Autores: César Fernández Domínguez, Isabel Fernández Esparza'
date: "Junio 2019"
output:
  html_document:
    highlight: default
    number_sections: yes
    theme: cosmo
    toc: yes
    toc_depth: 2
    includes:
      in_header: Practica2-header.html
  pdf_document:
    highlight: zenburn
    toc: yes
  word_document: default
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(eval=T, echo=T)
```
******
# Solución
******

## Descripción del dataset

Este dataset contiene información de estudiantes de matemáticas en edad de estudios secundarios. Se puede utilizar para analizar cómo afectan a los estudiantes de secundaria sus circunstancias personales a la hora de tener voluntad de continuar con estudios de mayor nivel. Estas circunstancias personales podemos entenderlas desde el punto de vista de: nivel de estudios de los padres, trabajo de los padres, si tienen pareja o no...
Por otro lado, también se podría hacer un análisis para estudiar la relación entre el número de suspensos de los estudiantes y el nivel de estudio de los padres, la distancia de los alumnos a los colegios, cómo influye el hecho de disponer de ayuda extraescolar en los resultados escolares, el tiempo de estudio semanal, el consumo de alcohol tanto diario como semanal, el número de ausencias...

El objetivo de esta práctica es limpiar los datos, unificarlos y poder estimar un modelo que pueda predecir el número de suspensos de un estudiante de matemáticas atendiendo a los factores anteriormente descritos. Teniendo en cuenta que en el juego de datos tenemos información de dos colegios diferentes podemos también intentar analizar si las predicciones realizadas están también sesgadas por el colegio al que pertenezcan los alumnos o por el sexo.

## Limpieza de datos

El fichero de datos contiene 396 registros y 33 variables. Las variables de las que disponemos son:

* school: colegio al que pertenece el alumno
* sex: sexo del alumno
* age: edad del alumno
* adrress: ubicación del alumno (rural o de ciudad)
* family size: tamaño de la familia
* Pstatus: padres separados o no
* Medu: nivel de educación de la madre
* Fedu: nivel de educación del padre
* Mjob: trabajo de la madre
* Fjob: trabajo del padre
* guardian: tutor
* traveltime: tiempo recorrido hasta llegar al colegio
* studytime: tiempo de estudio semanal del alumno
* failures: suspensos
* schoolsup: apoyo escolar
* famsup: disponen de ayuda en la educación en casa
* paid: recibe clases particulares pagadas
* activities: actividades extraescolares
* nursery: 
* higher: el alumno quiere realizar estudios superiores
* internet: el alumno tiene internet en casa
* romantic: el alumno tiene pareja o no
* famrel: calidad de las relaciones familiares
* freetime: tiempo libre al salir del colegio
* goout: el alumno sale con amigos
* dalc: consumo de alcohol diario
* walc: consumo de alcohol durante el fin de semana
* health: estado de salud del alumno
* absences: número de ausencias del alumno
* G1: nota en el primer trimestre
* G2: nota en el segundo trimestre
* G3: nota en el tercer trimestre

  




